# Generated by Django 6.0.1 on 2026-04-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='staff',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('paypal', 'PayPal')], default='cash', max_length=10),
        ),
    ]
